name: Continuous integration 

on: [push]

env:
  DOCKER_IMAGE: vmiko/hetzner-kube

jobs:
  build-push:
    name: Build and publish a docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Docker Tag
        run: echo "::set-env name=DOCKER_TAG::$([[ ${GITHUB_REF##*/} == "master" ]] && echo "latest" || echo ${GITHUB_REF##*/})"

      - name: Build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_IMAGE }}
          tag_with_ref: true
          push: false

      - name: Test
        run: docker run --rm ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} version

      - name: Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_IMAGE }}
          tag_with_ref: true
