name: Continuous integration 

on: [push]

env:
  DOCKER_IMAGE: vmiko/hetzner-kube

jobs:
  build:
    name: Build a docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Docker Tag
        run: echo "::set-env name=DOCKER_TAG::$([[ ${GITHUB_REF##*/} == "master" ]] && echo "latest" || echo ${GITHUB_REF##*/})"

      - name: Build
        run: docker build --build-arg VCS_REF=${GITHUB_SHA} --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .

      - name: Test
        run: docker run --rm ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} version

  push:
    name: Publish a docker image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set Docker Tag
        run: echo "::set-env name=DOCKER_TAG::$([[ ${GITHUB_REF##*/} == "master" ]] && echo "latest" || echo ${GITHUB_REF##*/})"

      - name: Push
        run: docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
